### ISSUE TITLE
Software and renderings

### ISSUE THREAD

**Issue by mado89** [m3y54m/pcb-esp32-s3-wroom-1-breakout-board#1]
Hi,
thanks for your project. Which software did you use for creating the schematic? Could you provide a pdf of the schematic and layout?

**Comment by m3y54m** [comment]
Hi,
I used Altium Designer to design both schematic and PCB layout. 
Currently I'm working on some issues in PCB layout. When it's finished I will commit the latest changes and add PDF of the schematic as you wanted.
